### ISSUE TITLE
"Fixes"

### ISSUE THREAD

**Issue by LordUbuntu** [neemspees/tragic-methods#14]
Would it be all-right to also add brief comments on workaround to language quirks for the curious in the directories of problems. For instance, [this python quirk]() can be worked around by changing the function from a default like:
```python
class Demo:
	"""A class representing a demo object with an ID"""
	def __init__(self,id = generate_id(6)):
		"""Instantiate the demo object with the ID from the 'id' parameter."""
		self.id = id
```
to instead take a function as an argument:
```python
class Demo:
	"""A class representing a demo object with an ID"""
	def __init__(self, id_func = generate_id, id_arg = 6):
		"""Instantiate the demo object with the ID from the 'id' parameter."""
		self.id = id_func(id_arg)
```

**Comment by neemspees** [comment]
You can update the README yourself and create a PR. 😄
