### ISSUE TITLE
Poor readability on Python example

### ISSUE THREAD

**Issue by jsbueno** [neemspees/tragic-methods#24]
https://github.com/neemspees/tragic-methods/blob/639f998c83f5e6c11c6dba655d0595663f56d504/python/capturing-variables/capturing_variables.py#L3

The line with the code that "does not work as intended" in the example is: 
```
funcs = [lambda: i for i in range(10)]
```

IMHO it is hard to get what is intended there, even for someone with a lot
of Python experience (at which point they will immediately figure out
the problem, due to have falling for this a couple of times already :-)  )

Just adding a pair parentheses  fore readability there might make things better:

```
funcs = [(lambda: i) for i in range(10)]
```

**Comment by neemspees** [comment]
Alright, that's a valid point. Could you make a PR for this?
