### ISSUE TITLE
Maybe require a proper readme.md for every submission

### ISSUE THREAD

**Issue by struffel** [neemspees/tragic-methods#3]
I think it would be a good idea to require a readme.md for every subfolder. That makes it easier to find interesting examples without needing to dive into the full code to learn what it's about from the comments.

GitHub renders readme.md files on its website for every folder, not just the root folder, so that would be an easy way to make the examples more accessible.

**Comment by neemspees** [comment]
@struffel, good point! It's added to the guidelines.
