### ISSUE TITLE
Reduce nesting

### ISSUE THREAD

**Issue by SpecificProtagonist** [neemspees/tragic-methods#6]
According to the contribution guidelines, each script should be placed in a separate sub-folder. This means the folder will be empty except for a single file, defeating the purpose of folders. Can we get rid of this layer of nesting and place the scripts directly in the language folder?

**Comment by struffel** [comment]
But some examples might need multiple files to work properly - that would get messy.
It also makes it more difficult to add a readme file for every example.

**Comment by neemspees** [comment]
Like @struffel pointed out, we need the sub-directories for to accommodate multiple files.
